x_variance: 0.01
W_variance: 0.01
slip_min: 0
slip_max: 2
tube_radius: 0.0762
tube_var: 0.00
tube_coordinates_x: [1,1,-1,-1,0.7,0,0,-0.8,0.5,-0.5]
tube_coordinates_y: [1,-1,1,-1,0,-0.8,0.7,0,0.5,-0.5]
max_distance: 0.8
range_min: 0.12
range_max: 3.5
angle_increment: 0.0175
resolution: 1
laser_var: 0.01
num_samples: 360
boarder_length: 3
boarder_width: 3