x_variance: 0.01
W_variance: 0.01
slip_min: 0
slip_max: 2
tube_radius: 0.0762
tube_var: 0.05
tube_coordinates_x: [1,1,-1,-1,2,2,-2,-2,2,1]
tube_coordinates_y: [1,-1,1,-1,2,-2,2,-2,1,2]
max_distance: 1
